/* SEER WARNS — landmark data for the interactive Harmon map.
   Pixel coordinates are in the max-zoom (z=3) coordinate space: 4096 x 2816.
   Positions are read directly off the painted Harmon map's labels. */

const MAP_W = 4096;
const MAP_H = 2816;
const MAX_ZOOM = 3;

const CATEGORIES = {
  seer:          { label: 'Seer encounter', color: '#a05030', glyph: '⚠' },
  establishment: { label: 'Establishment',  color: '#c08030', glyph: '☘' },
  civic:         { label: 'Civic',          color: '#5a7898', glyph: '⌂' },
  industrial:    { label: 'Industrial',     color: '#7a3a18', glyph: '⚙' },
  home:          { label: 'Home',           color: '#4a6028', glyph: '◉' },
  waterfront:    { label: 'Waterfront',     color: '#3a5878', glyph: '⚓' },
  neighborhood:  { label: 'Neighborhood',   color: '#8a6a3a', glyph: '✦' },
  route:         { label: 'Route',          color: '#5a4a36', glyph: '➔' },
};

// Positions sampled from the painted map. Each (px, py) is in 4096×2816 space.
const LANDMARKS = [
  // ── Downtown row of labeled signs (icon = upper-right corner of sign) ──
  {
    id: 'the-lamplighter',
    name: 'The Lamplighter',
    category: 'seer',
    px: 1627, py: 1084,
    address: 'Main Street, downtown — third booth on the right',
    blurb: 'The diner on Main Street where the Seer most often sits — but not the only place the Seer is found. Pouring the same coffee since 1977. The third booth on the right faces the front window; the vinyl is the color of dried blood, though no one who works here has ever called it that.',
    books: ['the-good-father', 'the-quiet-man'],
    seerScene: true,
    slug: 'the-lamplighter',
  },
  {
    id: 'roasters',
    name: 'Roasters',
    category: 'establishment',
    px: 1820, py: 1080,
    address: 'Main Street, between the Lamplighter and Haskell',
    blurb: 'The coffee shop tucked between the Lamplighter and Haskell Hardware. The smell of beans reaches both buildings.',
    books: ['the-good-father'],
    seerScene: false,
  },
  {
    id: 'haskell-hardware',
    name: 'Haskell Hardware',
    category: 'establishment',
    px: 2005, py: 1074,
    address: 'Main & Bridge, downtown — founded 1961',
    blurb: 'Founded 1961 by Boyd Haskell’s father. The bell on the door has rung the same way every Tuesday for sixty-three years. The pencil mark on the doorframe is Tyler’s last height, untouched since 2013.',
    books: ['the-quiet-man'],
    seerScene: false,
    slug: 'haskell-hardware',
  },
  {
    id: 'harmon-sentinel',
    name: 'Harmon Sentinel',
    category: 'civic',
    px: 2194, py: 1070,
    address: 'Main & Griffin, downtown',
    blurb: 'The town newspaper, on the downtown row between Haskell Hardware and First Federal. Gail Hendricks has edited it for thirty years; she is one of the people who stops calling Ruth Calloway in March. The paper covers everything — the foreclosure, the plant closure, the Bishop Hill bakery fire — in the same patient, archival voice.',
    books: ['the-good-father', 'the-honest-woman'],
    seerScene: false,
  },
  {
    id: 'first-federal',
    name: 'First Federal',
    category: 'civic',
    px: 2381, py: 1078,
    address: 'Main Street, downtown',
    blurb: 'Harmon’s main bank. The HELOC paperwork David Marsh forged Sarah’s signature on was processed through this branch. The bank started the foreclosure paperwork in October that no one in town saw until November.',
    books: ['the-good-father'],
    seerScene: false,
  },
  {
    id: 'the-barbershop',
    name: 'The Barbershop',
    category: 'establishment',
    px: 1683, py: 1209,
    address: 'Main Street south side, west end of the downtown row',
    blurb: 'The Main Street barbershop. Two chairs, a pole that hasn’t spun in twenty years, regulars who cut the same hair on the same days of the week. Where men in Harmon hear the news before their wives do.',
    books: [],
    seerScene: false,
  },
  {
    id: 'the-florist',
    name: 'The Florist',
    category: 'establishment',
    px: 1866, py: 1205,
    address: 'Main Street south side, between the barbershop and the dry cleaner',
    blurb: 'The Main Street florist. Small storefront on the south side of the row, between The Barbershop and The Dry Cleaner. The kind of place where you buy lilies for a funeral on a Thursday and they remember whose mother died.',
    books: ['the-good-father'],
    seerScene: false,
  },
  {
    id: 'the-dry-cleaner',
    name: 'The Dry Cleaner',
    category: 'establishment',
    px: 2050, py: 1211,
    address: 'Main Street south side, east of the florist',
    blurb: 'The downtown dry cleaner. The apartment above it is on Crane Street — the unit Elena Voss downsizes to after wiring her son the money.',
    books: ['the-keeper'],
    seerScene: false,
  },

  // ── Courthouse Square (label band at the building) ──
  {
    id: 'courthouse-square',
    name: 'Harmon County Courthouse',
    category: 'civic',
    px: 2070, py: 1450,
    address: 'Courthouse Square, downtown',
    blurb: 'The Harmon County Courthouse with its dome. The civic centerpiece of Courthouse Square. Where the records are kept. Where the falsified ones were filed for nineteen years before anyone was willing to read them.',
    books: ['the-honest-woman', 'the-good-brother'],
    seerScene: false,
  },
  {
    id: 'harmon-town-hall',
    name: 'Harmon Town Hall',
    category: 'civic',
    px: 1613, py: 1805,
    address: 'Courthouse Square, downtown',
    blurb: 'Ruth Calloway’s basement office is here — nineteen years of fluorescent light, three filing cabinets, the clerk’s window where residents come in to register a birth, a death, a deed. The water-quality reports sit in a drawer no one opens until Ruth does.',
    books: ['the-honest-woman'],
    seerScene: false,
  },
  {
    id: 'loring-finch',
    name: 'Loring & Finch, Architects',
    category: 'establishment',
    px: 2238, py: 1931,
    address: 'Washington Street, near Courthouse Square',
    blurb: 'The architecture firm Anne Loring built with her partner over twenty years. The ampersand on the door is the marriage of two names. When Anne files the audit, the ampersand comes off the door. The sign reads <em>Loring Architecture</em> by spring.',
    books: ['the-partner'],
    seerScene: false,
  },
  {
    id: 'bishop-hill-community-hall',
    name: 'Bishop Hill Community Hall',
    category: 'civic',
    px: 2818, py: 1608,
    address: 'Bishop Hill, north of the bakery',
    blurb: 'The neighborhood community hall on Bishop Hill. Where the block holds its summer cookout, its winter coat drive, its three-piece-band Saturdays. The hall keeps a small mimeographed history of the neighborhood on the back wall that nobody has updated since 1996.',
    books: [],
    seerScene: false,
  },
  {
    id: 'first-baptist-church',
    name: 'First Baptist Church',
    category: 'civic',
    px: 2590, py: 1755,
    address: 'Bishop Hill',
    blurb: 'The Baptist church with the white steeple at the heart of Bishop Hill. David Rourke has pastored this congregation for sixteen years. The congregation does not know he has lost his faith. The faith has been gone three years. The steeple has been the same steeple longer than the faith was ever there.',
    books: ['the-believer'],
    seerScene: false,
  },
  {
    id: 'st-annes-church',
    name: 'St. Anne’s Catholic Church',
    category: 'civic',
    px: 1263, py: 849,
    address: 'Fourth Street, North End',
    blurb: 'The Catholic parish church of the North End. The Torres family church for three generations — Ernesto’s funeral here, six weeks before Diana opens the drawer. The stained-glass window over the altar is the one Ernesto helped Torres Construction install in 1991.',
    books: ['the-inheritance'],
    seerScene: false,
  },
  {
    id: 'bishop-hill-bakery',
    name: 'Bishop Hill Bakery',
    category: 'establishment',
    px: 2830, py: 1784,
    address: 'Bishop Hill, south of the Community Hall',
    blurb: 'The neighborhood bakery on Bishop Hill. Open at five in the morning. The bread is good. The bell on the door rings the way Boyd Haskell’s bell rings, only different. The bakery has been the same bakery, in the same building, on the same street, since Boyd was a boy.',
    books: [],
    seerScene: false,
  },

  // ── East Side civic ──
  {
    id: 'st-clares-hospital',
    name: 'St. Clare’s Hospital',
    category: 'civic',
    px: 3594, py: 647,
    address: 'Cass & Church Street, East Side',
    blurb: 'The town’s hospital. Sarah Marsh works nights twice a week in the ER. Cat Brennan trauma-surgeries here. Luisa Dominguez doses the morphine drip in the ICU.',
    books: ['the-good-father', 'the-good-doctor', 'the-good-nurse'],
    seerScene: false,
  },
  {
    id: 'harmon-high-school',
    name: 'Harmon High School',
    category: 'civic',
    px: 3668, py: 787,
    address: 'East Side, beside the practice field',
    blurb: 'David Marsh teaches American history in Room 217; his window overlooks the practice field. Warren Gibbs teaches English on the floor below.',
    books: ['the-good-father', 'the-teacher'],
    seerScene: false,
  },
  {
    id: 'harmon-elementary',
    name: 'Harmon Elementary',
    category: 'civic',
    px: 3648, py: 1162,
    address: 'East Side, south of Harmon High',
    blurb: 'The town’s elementary school. Cooper Marsh attends third grade here; David walks past the front entrance on his Sunday drives to Lakeview Memory Care.',
    books: ['the-good-father'],
    seerScene: false,
  },
  {
    id: 'vfw-hall',
    name: 'VFW Hall',
    category: 'civic',
    px: 3175, py: 1608,
    address: 'Bishop Hill, near the Methodist Church',
    blurb: 'The Veterans of Foreign Wars hall. Fish fry on Fridays. Bingo on Tuesdays. The flag in the front window has not been lowered for eleven years — not since Tyler Haskell. Boyd has a folding chair he keeps in the back for the meetings he does not always attend.',
    books: ['the-quiet-man'],
    seerScene: false,
  },

  // ── The Flats: the plant ──
  {
    id: 'calloway-harmon-plant',
    name: 'Calloway–Harmon Plant',
    category: 'industrial',
    px: 761, py: 648,
    address: 'The Flats, along the Harmon River',
    blurb: 'The pork plant. Six hundred jobs at its peak; two hundred on the night shift before it closed in December 2024. Twenty-five years of falsified water-quality reports. The cadmium reached the lake.',
    books: ['the-honest-woman'],
    seerScene: false,
    slug: 'calloway-harmon-plant',
  },
  {
    id: 'torres-construction',
    name: 'Torres Construction',
    category: 'industrial',
    px: 1354, py: 980,
    address: 'North End, edge of the Flats',
    blurb: 'The construction company Ernesto Torres founded after he immigrated. He built much of the North End — block by block, brick by brick — and most of the houses his children grew up walking past. The yard is still in business under Diana’s brother. The framed first-dollar Ernesto ever earned is still on the office wall.',
    books: ['the-inheritance'],
    seerScene: false,
  },
  {
    id: 'grain-elevator',
    name: 'Grain Elevator',
    category: 'industrial',
    px: 955, py: 1021,
    address: 'On the rail spur, West Edge',
    blurb: 'The grain elevator on the rail spur. Visible from Route 9 coming into town from Marl. The trains still come, less often than they did. The fairgrounds beside it hold the Harmon County Fair one week each August.',
    books: [],
    seerScene: false,
  },

  // ── Waterfront (lake labels are at top of map already) ──
  {
    id: 'lake-harmon',
    name: 'Lake Harmon',
    category: 'waterfront',
    px: 2786, py: 366,
    address: 'The town’s northern boundary',
    blurb: 'The town’s drinking water source. The town’s public beach. The lake the children swam in every summer for fifty years. The cadmium stayed concentrated in the nearshore shallows, worst in June.',
    books: ['the-honest-woman', 'the-saved-woman'],
    seerScene: false,
  },
  {
    id: 'harmon-harbor-marina',
    name: 'Harmon Harbor Marina',
    category: 'waterfront',
    px: 964, py: 293,
    address: 'Foot of Mill Street, on the lake',
    blurb: 'Nora Finch runs the marina. The only outdoor Seer encounter in the series happens at the end of this dock, on a Tuesday in October, with the wind off the water.',
    books: ['the-saved-woman'],
    seerScene: true,
  },
  {
    id: 'bridgeport-tunnel',
    name: 'Bridgeport Tunnel',
    category: 'civic',
    px: 1316, py: 300,
    address: 'Route 11 N, under Lake Harmon',
    blurb: 'The Harmon Tunnel — the mid-twentieth-century public-works tunnel that carries Route 11 north under Lake Harmon to Bridgeport. The short way north when the long way takes five hours. The tile inside is the original tile. The light is the original light. Frank Morrow drives back through this tunnel after fifteen years.',
    books: ['the-prodigal'],
    seerScene: false,
  },

  // ── Neighborhoods ──
  {
    id: 'the-north-end',
    name: 'The North End',
    category: 'neighborhood',
    px: 1761, py: 632,
    address: 'The town’s oldest grid — First through Fourth Street',
    blurb: 'The oldest neighborhood in Harmon, by the river, on the numbered grid surveyors laid out at the turn of the century. Small hundred-year-old houses. St. Anne’s Catholic Church on Fourth Street. Riverside Park with its ball diamond. Where the Marsh family grew up, where the Torres family built its brick house, where the town remembers its early shape.',
    books: ['the-good-father', 'the-inheritance'],
    seerScene: false,
  },
  {
    id: 'downtown',
    name: 'Downtown',
    category: 'neighborhood',
    px: 2392, py: 944,
    address: 'Main Street, between Mill and Park',
    blurb: 'The town’s commercial heart. The Lamplighter, Roasters, Haskell Hardware, Harmon Sentinel, First Federal — the row of shops that has been the row of shops since the Eisenhower administration. The Varsity Theater’s art-deco marquee still works. The Anchor Tap still pours. Downtown is where the town meets itself.',
    books: ['the-good-father', 'the-honest-woman', 'the-quiet-man'],
    seerScene: false,
  },
  {
    id: 'the-east-side',
    name: 'The East Side',
    category: 'neighborhood',
    px: 3147, py: 849,
    address: 'East of Downtown',
    blurb: 'The newer half of Harmon. St. Clare’s Hospital. Harmon High. Harmon Elementary. The residential streets where Sarah Marsh’s sister rents a duplex; where Cat Brennan’s late husband built the colonial on Vine Street; where the Bishop Hill neighborhood begins. Greener, gridded later, less storied than the North End.',
    books: ['the-good-father', 'the-good-doctor', 'the-teacher'],
    seerScene: false,
  },
  {
    id: 'bishop-hill',
    name: 'Bishop Hill',
    category: 'neighborhood',
    px: 2688, py: 1482,
    address: 'East Side, German-American neighborhood',
    blurb: 'The German-American neighborhood on the east-central edge of town. Vine Street, Walnut, Pine. Two-story colonials with wraparound porches. The Bishop Hill Community Hall, the Bishop Hill Bakery, the First Baptist Church. Where Cat Brennan’s house has been her house since her husband finished framing it in 2012.',
    books: ['the-good-doctor', 'the-quiet-man'],
    seerScene: false,
  },
  {
    id: 'pinewood-subdivision',
    name: 'Pinewood Subdivision',
    category: 'neighborhood',
    px: 3828, py: 1614,
    address: 'East Side, on Maple Drive',
    blurb: 'A 1990s HOA development on the East Side. Identical Craftsman bungalows on quarter-acre lots, all the same trim colors, all the same front porches. Elena Voss lives in the one on Maple Drive — for thirty years, the same garden, the same dahlias, the same gray tabby in the window. Kevin Reilly’s four-bedroom colonial is two streets over.',
    books: ['the-keeper', 'the-good-brother'],
    seerScene: false,
  },
  {
    id: 'elm-street-park',
    name: 'Elm Street Park',
    category: 'civic',
    px: 3396, py: 1814,
    address: 'East Side, on Elm Street',
    blurb: 'The neighborhood park with the Little League diamond where Cooper Marsh plays Saturday mornings. The bleachers fit forty parents; on a good morning thirty come. The chain-link backstop has been the same chain-link backstop since David Marsh was Cooper’s age.',
    books: ['the-good-father'],
    seerScene: false,
  },

  // ── Routes leaving Harmon ──
  {
    id: 'route-9-marl',
    name: 'Route 9 ← Marl',
    category: 'route',
    glyph: '←',
    px: 292, py: 1406,
    address: 'Westbound out of town',
    blurb: 'Route 9 west, the rural road to Marl — small neighbor town, rural eldercare beyond. The road to Lakeview Memory Care (22 minutes) and Pine Ridge Senior Care (30 minutes). The road David Marsh drives every Sunday to sit with Helen.',
    books: ['the-good-father'],
    seerScene: false,
  },
  {
    id: 'route-9-hartwick',
    name: 'Route 9 → Hartwick',
    category: 'route',
    glyph: '→',
    px: 3861, py: 1423,
    address: 'Eastbound out of town',
    blurb: 'Route 9 east, the road to Hartwick — larger neighbor town, home of Hartwick College and the county recorder’s office. Forty-five minutes from Harmon. Where Claire Novak teaches the writing workshop at the college, and where the <em>Hartwick Gazette</em> covers what the <em>Harmon Sentinel</em> doesn’t.',
    books: ['the-last-one'],
    seerScene: false,
  },
  {
    id: 'route-11-granger',
    name: 'Route 11 ↓ Granger',
    category: 'route',
    glyph: '↓',
    px: 2301, py: 2580,
    address: 'Southbound out of town',
    blurb: 'Route 11 south, the long-haul road to the state capital, then Granger (the big-money developer city), and on toward Fenmore (federal correctional facility, four hours). The road Maggie Caldwell takes to meet the Whitfield contract people. The road Diana Torres drives away from her father’s funeral.',
    books: ['the-builder', 'the-inheritance'],
    seerScene: false,
  },

  // ── North End homes (approximate — painted map doesn't label specific houses) ──
  // Click the actual painted house you want and send me coords to refine these.
  {
    id: 'marsh-house',
    name: 'The Marsh House',
    category: 'home',
    px: 2000, py: 670,
    address: '1847 Third Street, North End',
    blurb: 'David Marsh grew up in this house. He loses it the November after the Seer names the date. By Thanksgiving the file box marked “taxes” is in the wrong hands. <em>Painted as one of these North End houses — the exact lot is the reader’s.</em>',
    books: ['the-good-father'],
    seerScene: false,
  },
  {
    id: 'torres-house',
    name: 'The Torres House',
    category: 'home',
    px: 1774, py: 859,
    address: 'Riverside Avenue, North End — just south of Torres Construction',
    blurb: 'The brick house Ernesto Torres built in 1986, where his widow still lives. The locked drawer Diana finds during the estate cleanout contains forty years of cancelled checks. <em>Painted as one of these North End houses, on a residential street south of the construction yard the family built.</em>',
    books: ['the-inheritance'],
    seerScene: false,
  },

  // ── West Edge ──
  {
    id: 'west-edge-otb',
    name: 'West Edge OTB',
    category: 'establishment',
    px: 794, py: 1584,
    address: 'Strip mall off Route 9, beside the grain elevator',
    blurb: 'The off-track-betting parlor in the half-tenanted strip mall on the west edge of town. David Marsh learned the geometry of this room the way he learned Civil War casualty figures.',
    books: ['the-good-father'],
    seerScene: false,
  },
  {
    id: 'farm-supply',
    name: 'Farm Supply',
    category: 'establishment',
    px: 680, py: 1798,
    address: 'Route 9, West Edge',
    blurb: 'The farm-supply store along Route 9 at the West Edge. Feed, fence wire, oil, gloves, the smell of bagged grain and diesel. The kind of place where every farmer for thirty miles knows the man behind the counter, and the man behind the counter knows their fathers.',
    books: [],
    seerScene: false,
  },
  {
    id: 'burger-joint',
    name: 'Burger Joint',
    category: 'establishment',
    px: 538, py: 1950,
    address: 'Route 9, far West Edge',
    blurb: 'The roadside burger stand at the western edge of town, the last commercial building before the rural eldercare road. Open from eleven until eight. Three booths inside, a window for the highway. The kind of place where you eat with one hand on the wheel because the parking lot is also the highway.',
    books: [],
    seerScene: false,
  },

  // ── Big-box stores along the Harmon Bypass ──
  {
    id: 'harmon-supercenter',
    name: 'Harmon Supercenter',
    category: 'establishment',
    px: 1571, py: 2176,
    address: 'Harmon Bypass, south of downtown',
    blurb: 'The first of the big-box stores that opened along the bypass when the bypass opened. Where Harmon goes for the things Main Street no longer carries. The parking lot is full on Saturdays and empty on Tuesdays in a way the downtown never is.',
    books: [],
    seerScene: false,
  },
  {
    id: 'valuemart',
    name: 'ValueMart',
    category: 'establishment',
    px: 2247, py: 2173,
    address: 'Harmon Bypass, between Supercenter and HomePlus',
    blurb: 'The middle big-box store on the bypass. Cheaper than Supercenter, narrower than HomePlus. The kind of store Elena Voss starts driving to instead of Main Street the same year she starts wiring money to her son.',
    books: ['the-keeper'],
    seerScene: false,
  },
  {
    id: 'homeplus',
    name: 'HomePlus',
    category: 'establishment',
    px: 2978, py: 2141,
    address: 'Harmon Bypass, south of downtown',
    blurb: 'The big-box hardware-and-home retailer whose grand-opening insert lands on Boyd Haskell’s kitchen table the morning after the Lamplighter encounter. The smiling cashier on the circular has Boyd’s eldest customer’s face, more or less. Boyd does not finish the coffee.',
    books: ['the-quiet-man'],
    seerScene: false,
  },
  {
    id: 'harmon-cemetery',
    name: 'Harmon Cemetery',
    category: 'civic',
    px: 3920, py: 2110,
    address: 'East of town off Route 6',
    blurb: 'The town’s cemetery. Where Helen Marsh is buried after the funeral David nearly misses. Where Ernesto Torres is buried six weeks before Diana finds the drawer. Where Tyler Haskell isn’t — Tyler is in a flag-draped plot at a national cemetery in another state — but his name is on the stone here next to his parents’ plot, waiting.',
    books: ['the-good-father', 'the-inheritance', 'the-quiet-man'],
    seerScene: false,
  },

  // ── Seer encounters that happen off the Lamplighter (placement is approximate) ──
  {
    id: 'hartwick-license-bureau',
    name: 'Hartwick License Bureau',
    category: 'seer',
    px: 3950, py: 1450,   // far east edge — off-map toward Hartwick; tune via ?debug
    address: 'Route 9 east — strip mall in Hartwick (45 minutes out)',
    blurb: 'A regional license bureau in a strip mall in Hartwick, between a dry cleaner and a seasonal tax-prep office. The county recorder’s office is in the same building — different floor, different entrance. Ruth drove the forty-five minutes because the Harmon bureau is closed Wednesdays. The woman at the counter took her photograph, then sat down across from her in the waiting area without being called. The numbers on the LED board froze mid-blink.',
    books: ['the-honest-woman'],
    seerScene: true,
    glyph: '⚠',
  },
  {
    id: 'route-22-stop',
    name: 'Route 22 Bus Stop',
    category: 'seer',
    px: 2080, py: 1300,   // approximate — downtown, near the assessor's office Dennis would board from
    address: 'Eastbound 7:14, downtown stop near the assessor’s office',
    blurb: 'Dennis Reilly boards the eastbound 7:14 on the days his car won’t start. A passenger in a sun-faded jacket boards two stops later, sits across the aisle, never reaches for a phone. The bus is half-empty. The brakes hiss. The voice begins.',
    books: ['the-good-brother'],
    seerScene: true,
  },
  {
    id: 'route-6-rest-stop',
    name: 'Route 6 Rest Stop',
    category: 'seer',
    px: 3920, py: 2700,   // approximate — bottom-right of the map, near the Route 6 east-bound label
    address: 'Eastbound Route 6, twenty minutes before town',
    blurb: 'Jack Callahan stops for coffee at the rest stop twenty minutes before town. He has not been on this road in twenty-five years. A stranger holding a styrofoam cup with both hands tells Jack what going home is going to cost. Jack drives the last twenty minutes anyway.',
    books: ['the-accused-man'],
    seerScene: true,
  },
];

if (typeof window !== 'undefined') {
  window.CATEGORIES = CATEGORIES;
  window.LANDMARKS = LANDMARKS;
  window.MAP_W = MAP_W;
  window.MAP_H = MAP_H;
  window.MAX_ZOOM = MAX_ZOOM;
}
